### ISSUE TITLE
hbuilder怎么集成极光推送,官方demo没看明白

### ISSUE THREAD

**Issue by david-wei-zh** [jpush/jpush-api-java-client#104]
怎么在hbuilder里面配置极光!

**Comment by KenChoi1992** [comment]
@david-wei-zh https://github.com/jpush/jpush-hbuilder-demo

**Comment by david-wei-zh** [comment]
就是这个demo没看明白 里面又是android又是ios  在hbuild哪里能配置这些

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/35850091-ae97fe58-0b5e-11e8-88bd-e5e25ff49047.png)

**Comment by david-wei-zh** [comment]
cn.jpush.android.api.JPushInterface 错误  Unused import statement

**Comment by david-wei-zh** [comment]
不报错了  怎么调试才知道能用?

**Comment by JoshLipan** [comment]
hbuilder相关问题请提到https://github.com/jpush/jpush-hbuilder-demo
