### ISSUE TITLE
http状态为400时，HttpResponseHandler中计数器不能减一，导致发送过程block住

### ISSUE THREAD

**Issue by ArnoldYang** [jpush/jpush-api-java-client#115]
下面这个问题有人遇到过不？也有可能是我配置的原因，比较奇怪，前几天都可以，代码没有改动，最近就不行了。

1# cn.jiguang.common.connection.NettyHttpClient#sendHttpRequest 创建CountDownLatch执行发送，等待返回结果。
2# 发送完毕，服务器返回结果交给HttpResponseHandler处理，msg为DefaultLastHttpContent执行了if分支，_latch计数器没有减掉，导致1#被block住。
```
if(msg instanceof HttpContent) { // msg为DefaultLastHttpContent，实现接口LastHttpContent
    HttpContent content1 = (HttpContent)msg;
    LOG.info(content1.content().toString());
    if(content1 instanceof LastHttpContent) {
	LOG.info("closing connection");
	ctx.close();
    } else {
	// ...
	if(null != this._latch) {
	    this._latch.countDown();
	}
    }
}
```
相关信息：
推送结果：发送失败(errcode:1011,errmsg:没有满足条件的推送目标)
响应信息：
DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 21 Jun 2018 01:25:01 GMT
Content-Type: application/json
Content-Length: 91
Connection: keep-alive
X-Rate-Limit-Limit: 600
X-Rate-Limit-Remaining: 599
X-Rate-Limit-Reset: 60
X-Jpush-Msgid: 2209689839

DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 91, cap: 91/91, unwrapped: PooledUnsafeDirectByteBuf(ridx: 352, widx: 352, cap: 381)), decoderResult: success)

**Comment by ArnoldYang** [comment]
极光后台是可以看到推送结果，就是api推消息的时候一直被blok住。
版本是3.2.15，对比看了一下最新的3.3.7，相关部分的代码是一样的。

**Comment by JoshLipan** [comment]
参照[这个提问](https://community.jiguang.cn/t/topic/27650)

**Comment by ArnoldYang** [comment]
@JoshLipan  看到了，现在可以跑了，谢谢了
