### ISSUE TITLE
v3/grouppush 是不是只支持 audience 为all的情况，我用别名总是返回1011，无法找到目标

### ISSUE THREAD

**Issue by qjyoung** [jpush/jpush-api-java-client#120]
### 但是用官方控制台推送却能成功，是不是需要自己写方法分别推送
![123](https://user-images.githubusercontent.com/25897599/45616598-872ad680-baa2-11e8-81dd-e6f1a631f2e4.png)

**Comment by Lris12J** [comment]
1、分组推送，必须使用对应机房的域名，如应用在北京机房，则必须更换为北京机房的 API 地址
https://community.jiguang.cn/t/jpush/5145/38
2、若使用别名推送，报错 1011，代表你们别名没设置成功，检查
https://community.jiguang.cn/t/jpush/5145/10
