### ISSUE TITLE
JPush推送数据类型有限？

### ISSUE THREAD

**Issue by Mr-LiuDC** [jpush/jpush-api-java-client#129]
请问JPush推送数据类型只能是String类型吗？在使用JPush服务端SDK发送自定义消息时，如果附加字段中有`boolean`或者`int`类型会报类型转换错误，加上引号就没问题了。
`java.lang.Integer cannot be cast to java.lang.String`
`java.lang.Boolean cannot be cast to java.lang.String`

**Comment by JoshLipan** [comment]
支持，可以[直接设置 Boolean 和 int 类型](https://github.com/jpush/jpush-api-java-client/blob/master/src/main/java/cn/jpush/api/push/model/Message.java#L143)。
