### ISSUE TITLE
无法setIntent

### ISSUE THREAD

**Issue by luodaozhang** [jpush/jpush-api-java-client#143]
当我构建PushPayload的时候如果我不setInbox,就无法setIntent
![DeepinScreenshot_select-area_20190830184823](https://user-images.githubusercontent.com/34682320/64015277-c12ba600-cb56-11e9-8ece-eeb767f71f3f.png)
![DeepinScreenshot_select-area_20190830184719](https://user-images.githubusercontent.com/34682320/64015195-9a6d6f80-cb56-11e9-9e29-5480dda6a18d.png)
![DeepinScreenshot_select-area_20190830184358](https://user-images.githubusercontent.com/34682320/64015114-63975980-cb56-11e9-9f31-2126fab4abc9.png)
![DeepinScreenshot_select-area_20190830184431](https://user-images.githubusercontent.com/34682320/64015119-65611d00-cb56-11e9-9e48-b7da757d383d.png)

**Comment by SlipChik** [comment]
已修改
