### ISSUE TITLE
这就是所谓的文档吗？

### ISSUE THREAD

**Issue by aboutZZ** [jpush/jpush-api-java-client#147]
方法是干嘛的，参数是什么含义，一概没有。
`setStyle`方法传入一个int值，这个值可以是多少？文档呢？
我服了。
恕我直喷：还不如不写。估计也就是个KPI产物，草草敷衍了事

[![uJF1je.png](https://s2.ax1x.com/2019/09/30/uJF1je.png)](https://imgchr.com/i/uJF1je)

**Comment by KitGavinx** [comment]
和没看没什么区别

**Comment by saymimo** [comment]
真是有够好笑呢

**Comment by SlipChik** [comment]
https://docs.jiguang.cn/jpush/server/push/server_overview/
请参考最新文档
