### ISSUE TITLE
这是什么垃圾官方文档?注释也没有,内容都是错的,垃圾

### ISSUE THREAD

**Issue by www6223166** [jpush/jpush-api-java-client#149]
这是什么垃圾官方文档?注释也没有,内容都是错的,垃圾

**Comment by 3ono3** [comment]
https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/

**Comment by www6223166** [comment]
作为官方Demo,API是过时的,代码混乱,没有任何注释,编译都是报错的,找寻可以用的Demo只能到别人的博客下找,无力吐槽

**Comment by 13661411934** [comment]
官方一个issue都没回应阿

**Comment by KitGavinx** [comment]
辣鸡文档

**Comment by Stone-yu** [comment]
垃圾文档
