### ISSUE TITLE
消息撤回方法是哪个方法？在sdk里好像没找到

### ISSUE THREAD

**Issue by shenshihala** [jpush/jpush-api-java-client#162]
如题
推送撤销
调用地址
DELETE https://api.jpush.cn/v3/push/{msgid}

功能说明
撤销操作首先会从服务端尝试撤销（Android消息，排队中/发送中状态可以服务端撤销；iOS消息，排队中状态可以服务端撤销）；其次，针对 Push SDK（JPush Android SDK v3.5.0 及以上和 JPush iOS SDK v3.2.8 及以上），会尝试从设备端撤销已展示但未被点击的消息。

**Comment by OuDale** [comment]
+1  为啥这么简单的一个接口都没有实现？

**Comment by yutaipu** [comment]
3.4.7已经提供此接口
