### ISSUE TITLE
怎么设置uri_activity,uri_action等一些通知的可选参数？

### ISSUE THREAD

**Issue by Winemusic** [jpush/jpush-api-java-client#164]

**Comment by cnkaile** [comment]
同问

**Comment by cnkaile** [comment]
看了下源码，用这个
`cn.jpush.api.push.model.notification.PlatformNotification.Builder#addCustom(java.lang.String, java.lang.String)`

**Comment by SlipChik** [comment]
现在已添加支持setUriActivity, setUriAction
