### ISSUE TITLE
SDK中的极光推送服务地址有修改的接口吗？

### ISSUE THREAD

**Issue by doudou459** [jpush/jpush-api-java-client#173]
因为生产环境服务器是不能直接访问外网的，所以需要代理，那么我们极光服务就需要请求这个代理地址，SDK有修改服务地址的接口吗？

**Comment by yutaipu** [comment]
JPushClient和PushClient构造方法都有HttpProxy参数

**Comment by doudou459** [comment]
好的，收到！
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpush/jpush-api-java-client"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月21日(星期一) 中午11:06
收件人:&nbsp;"jpush/jpush-api-java-client"<jpush-api-java-client@noreply.github.com&gt;;
抄送:&nbsp;"空白"<459349489@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jpush/jpush-api-java-client] SDK中的极光推送服务地址有修改的接口吗？ (#173)





 
JPushClient和PushClient构造方法都有HttpProxy参数
