### ISSUE TITLE
Dependency 'cn.jpush.api:jpush-client:3.4.7' not found 

### ISSUE THREAD

**Issue by Hidoikoto** [jpush/jpush-api-java-client#178]
在pom.xml里加了依赖报红啊？怎么集成

**Comment by SlipChik** [comment]
请填写最新版本号

**Comment by SlipChik** [comment]
![image](https://user-images.githubusercontent.com/38679446/127956226-3695d47a-6b6c-40eb-9992-217ccc976cf2.png)
