### ISSUE TITLE
极光推送，最近老报这个错 cannot find user by this audience or has been inactive for more than 255 days 

### ISSUE THREAD

**Issue by nihao12358** [jpush/jpush-api-java-client#179]
极光推送，最近老报这个错 cannot find user by this audience or has been inactive for more than 255 days 

![image](https://user-images.githubusercontent.com/5662431/99232030-584c4e80-282c-11eb-930c-506991f7678b.png)

**Comment by bigwhiterice** [comment]
老哥现在有解决办法么？ 我找技术支持他们说是让升级下版本

**Comment by hupantingxue** [comment]
这个从错误码看，是因为没有目标用户或者用户不活跃导致的。
可以看文档关于1011错误码的描述：
http://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/

**Comment by zlay0701** [comment]
因为没标签啊  客户端需要打上对应的标签

**Comment by zlay0701** [comment]
有标签才能发出去

**Comment by zlay0701** [comment]
你发推送的时候 就是按标签推的吗  服务器没这个标签就这个错
