### ISSUE TITLE
自定义消息添加拓展参数这里是个bug吗？

### ISSUE THREAD

**Issue by Yc-coder** [jpush/jpush-api-java-client#188]
通过 cn.jpush.api.push.model.Message.class  addExtra(String key, JsonObject value)添加json自定义参数，toJSON方法里是有个bug吗？：
if (null != extras || null != numberExtras || null != booleanExtras) {
            json.add(EXTRAS, extrasObject);
        }
只有extras ，numberExtras ，booleanExtras才能添加到自定以参数里？？

**Comment by SlipChik** [comment]
已修改
