### ISSUE TITLE
Message$Builder.addExtras(Map<String, String> extras) 限制了只能添加string类型参数

### ISSUE THREAD

**Issue by hoswey** [jpush/jpush-api-java-client#33]
Message$Builder.addExtras(Map&lt;String, String> extras)

建议该方法Map改为 Map&lt;String,Object>, 这样直接添加Map才不会受到只能添加字符串的限制，这样可满足如添加此类json的限制

```javascript
｛
    type : 1
    data: {
        userName: "xxx",
        age : 18
   }
｝
```

对于Object的支持类型，可再内部做进一步校验

**Comment by Liuchy1** [comment]
可提交merge request 到 dev 分支，欢迎各位开发者贡献代码。
