### ISSUE TITLE
关于PushResult和ResponseWrapper序列化问题

### ISSUE THREAD

**Issue by xps-zzq** [jpush/jpush-api-java-client#50]
在构建推送的时候  采用dubbo的远程调用服务时 出现该2个类无法序列化。原因是这两个类没有实现序列化接口。通过修改该项目打包到maven里面引用解决了该问题 希望改掉这个问题。如有不清楚的问题
请联系 qq 496268609。(顺便说一句 默认构造器和实现序列化接口不是JavaBaan规范么);

**Comment by Liuchy1** [comment]
多谢提交问题，后续修改，也希望可以提交pull request。

**Comment by Liuchy1** [comment]
v3.2.9 release 修复此问题。
