### ISSUE TITLE
java client推送notification，包括iOS和Android，调用extras增加一个字段，应该调用哪个接口

### ISSUE THREAD

**Issue by xeostream** [jpush/jpush-api-java-client#51]
在java接口文档中看到的增加附加字段的话，都是区分平台（iOS和Android）的，想知道如果不区分平台的话，应该如何调用接口

**Comment by Liuchy1** [comment]
如果没有现成的方法的话，可以用PushPayload构建自己想要的推送内容。

**Comment by bdqy** [comment]
建议Notification添加Extras的方法

**Comment by sunkaigoon** [comment]
`Notification`
	`.newBuilder()`
		`.addPlatformNotification(`
		     `AndroidNotification`
		     `.newBuilder()`
		     `.addExtras(extras)`
		     `.setAlert(alert)`
		     `.setTitle(title)`
		     `.build()`
		`)`
		`.addPlatformNotification(`
                         `IosNotification`
			`.newBuilder()`
			`.addExtras(extras)`
			`.setAlert(alert)`
			`.autoBadge()`
			`.build())`
		 `.build()`
	`).setPlatform(Platform.android_ios());`
