### ISSUE TITLE
定时推送如何实现上午9点-10点，每隔10分钟推送

### ISSUE THREAD

**Issue by houguiqiang** [jpush/jpush-api-java-client#68]
定时推送如何实现上午9点-10点，每隔10分钟推送，貌似不支持。最小粒度是day的

**Comment by KenChoi1992** [comment]
@houguiqiang http://docs.jiguang.cn/server/rest_api_v3_push/#options 文档上有个 big_push_duration 选项，可以按分钟定速推送
