### ISSUE TITLE
离线消息推送不到客户端呢？

### ISSUE THREAD

**Issue by wangyang135** [jpush/jpush-api-java-client#69]
// 封装数据
				JSONObject jsonObject = new JSONObject();

				jsonObject.put("platform", "all");
				JSONArray jsonArray = new JSONArray();
				JSONObject alias = new JSONObject();
                                // 用户名为其别名
				jsonArray.add(user.getUserName());
				alias.put("alias", jsonArray);
				
				jsonObject.put("audience", alias);
				
				//jsonObject.put("audience", "all");
				JSONObject notification = new JSONObject();
				notification.put("alert", "Hello" );
				jsonObject.put("notification", notification);
				
				JSONObject timeToLive = new JSONObject();
				timeToLive.put("time_to_live", 0);
				jsonObject.put("options", timeToLive);

**Comment by KenChoi1992** [comment]
用的哪一个API？用PushPayload的build方法来构造一个payload对象试试？

**Comment by wangyang135** [comment]
@KenChoi1992 我用的是json数据，封装好然后调用极光的接口，这里的别名需要和注册id绑定吗

**Comment by KenChoi1992** [comment]
@wangyang135 如果按照alias推送，一定要绑定注册id的

**Comment by wangyang135** [comment]
@KenChoi1992  谢谢啦，确实是你说的要绑定注册id的
