### ISSUE TITLE
别名支持特殊字符减号

### ISSUE THREAD

**Issue by xiemeilong** [jpush/jpush-api-java-client#72]
别名为什么不支持减号字符啊，别名是程序使用的，不需要有可读性，干嘛要限定字符呢。而且减号也是url安全的。

请问你们能改成支持减号字符吗？

**Comment by KenChoi1992** [comment]
@xiemeilong 下个版本支持。

**Comment by KenChoi1992** [comment]
@xiemeilong 现在已经支持特殊字符了
