### ISSUE TITLE
jpush发送通知400错误

### ISSUE THREAD

**Issue by geosmart** [jpush/jpush-api-java-client#73]
由于jpush-client依赖的jar和系统框架的一些jar冲突，只能自己参考[Jpush服务端 REST API 概述](https://docs.jiguang.cn/jpush/server/push/server_overview/)封装实现，但是调用总报400错误：
```java
java.io.IOException: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

但是同样的json和appKey以及masterSecret，用postman或curl能正常调用，请教下是什么原因。

**Comment by geosmart** [comment]
已解决了，是httpclient的https协议问题，有需要的可参考[me.demo.jpush-基于jpush的rest api实现的java通知服务端](https://github.com/geosmart/me.demo.jpush)

**Comment by KenChoi1992** [comment]
那就关掉这个 issue 了
