### ISSUE TITLE
v3.2.15 Release 中增加的NettyHttpClient无法捕获APIConnectionException, APIRequestException异常

### ISSUE THREAD

**Issue by thinktkj** [jpush/jpush-api-java-client#76]
v3.2.15 Release 中增加的NettyHttpClient无法捕获APIConnectionException, APIRequestException异常
看了下源码
这能抛出异常么？
**_@Override
    public ResponseWrapper sendPost(String url, String content) throws APIConnectionException, APIRequestException {
        ResponseWrapper wrapper = new ResponseWrapper();
        try {
            return sendHttpRequest(HttpMethod.POST, url, content);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return wrapper;
    }_**

**Comment by thinktkj** [comment]
@KenChoi1992 问题是我怎么判断状态码呢？在线等

**Comment by KenChoi1992** [comment]
```
PushResult result = jpushClient.sendPush(payload);
int status = result.getResponseCode();
```

**Comment by thinktkj** [comment]
@KenChoi1992 我说的是错误码，不是http状态码！！！
我需要知道设备是否已注销，1011这个。。。

**Comment by thinktkj** [comment]
需要自己改源码，加close，还要自己解析错误码

你们还主动关闭问题，我也是醉了。。。

**_PushResult result = pushClient.sendPush(pushPayload);
            if (result.isResultOK()) {
                logger.info("推送成功, Message: " + paramsMesage);
            } else {
                // 分析请求结果
                String resultContent = result.getOriginalContent();
                // 错误信息
                JSONObject error = JSON.parseObject(resultContent).getJSONObject("error");
                if (error != null && error.getIntValue("code") == 1011) {
                    // 缓存推送
                    messageDAO.insertPushMessage(uid, paramsMesage);
                    logger.warn("推送已延迟, Result: 用户已注销或者登录了非移动终端(如WEB), Message: " + paramsMesage);
                } else {
                    logger.error("推送失败, HTTP Status: " + result.getResponseCode() + ", ResultContent: " + resultContent + ", Message: " + paramsMesage);
                }
            }
            pushClient.close();_**
