### ISSUE TITLE
jpush-client jar依赖不到，是不是没有打到仓库中？

### ISSUE THREAD

**Issue by AndyAndAndy** [jpush/jpush-api-java-client#81]
jpush-client jar依赖不到，是不是没有打到仓库中？
<dependency>
    <groupId>cn.jpush.api</groupId>
    <artifactId>jpush-client</artifactId>
    <version>3.2.18</version>
</dependency>

<version>3.2.17</version>

**Comment by KenChoi1992** [comment]
@AndyAndAndy  可以呀，我用的是 maven，没毛病。

**Comment by KenChoi1992** [comment]
@AndyAndAndy 这个问题你没回复，我先关掉了。
