### ISSUE TITLE
这个是什么情况下出现的

### ISSUE THREAD

**Issue by yulechen** [jpush/jpush-api-java-client#88]
cannot find user by this audience。

17/09/01 17:42:33 DEBUG connection.NativeHttpClient: Request Content - {"platform":["android","ios"],"audience":"all","notification":{"ios":{"alert":"你好","extras":{"type":"infomation"},"badge":"+1","sound":""},"android":{"alert":"你好","extras":{"type":"infomation"}}},"options":{"sendno":1742040373,"time_to_live":90,"apns_production":false}}
17/09/01 17:42:33 DEBUG resp.ResponseWrapper: JPush API Rate Limiting params - quota:600, remaining:599, reset:60
17/09/01 17:42:33 WARN connection.NativeHttpClient: Got error response - responseCode:400, responseContent:{"msg_id": 2081584083, "error": {"message": "cannot find user by this audience", "code": 1011}}
17/09/01 17:42:33 ERROR connection.NativeHttpClient: Your request params is invalid. Please check them according to error message.
17/09/01 17:42:33 ERROR test.Push: Error response from JPush server. Should review and fix it. 
{}
	at cn.jiguang.common.connection.NativeHttpClient._doRequest(NativeHttpClient.java:235)
	at cn.jiguang.common.connection.NativeHttpClient.doRequest(NativeHttpClient.java:99)
	at cn.jiguang.common.connection.NativeHttpClient.sendPost(NativeHttpClient.java:86)
	at cn.jpush.api.push.PushClient.sendPush(PushClient.java:163)
	at cn.jpush.api.JPushClient.sendPush(JPushClient.java:195)
	at com.cg.test.Push.testSendPush(Push.java:51)
	at com.cg.test.Push.main(Push.java:29)
17/09/01 17:42:33 INFO test.Push: HTTP Status: 400
17/09/01 17:42:33 INFO test.Push: Error Code: 1011
17/09/01 17:42:33 INFO test.Push: Error Message: cannot find user by this audience
17/09/01 17:42:33 INFO test.Push: Msg ID: 2081584083
17/09/01 17:42:33 ERROR test.Push: Sendno: 1742040373

**Comment by KenChoi1992** [comment]
@yulechen https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#_19

**Comment by yulechen** [comment]
是要有设备在线上 ，才能推送 。推送失败的时候 不会进行消息重发 ，是这样吗
