### ISSUE TITLE
源码可读性不高；是否可以添加注解？

### ISSUE THREAD

**Issue by hahafeixiu** [jpush/jpush-api-java-client#91]
1. PushPayload累中的字段各是什么用？具体到字段类里面有没有？除了example的方法名可以了解点东西之外，自己扩展起来又点耗时间，还需要通过验证看是否正确？
2. Pushapi里面结构跟代码中的结构又不一致～

**Comment by KenChoi1992** [comment]
@hahafeixiu  PushPayload 各字段跟文档上一样，名字对号入座。https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push/#platform
